### ISSUE TITLE
TypeError: object null is not iterable

### ISSUE THREAD

**Issue by Caballerog** [co-IT/ngrx-vis#10]
First of all, thank you very much for this project.

I have found the same error in two projects (one private and the other opensource). The opensource project code is here: https://github.com/Caballerog/ngrx-pokedex/tree/ngrx-part3

I have followed the installation and configuration steps as described in README and my output is as follows:

```
[carlos@carlos-lenovo ngrx-pokedex]$ npm run ngrx-vis

> ngrx-pokedex@0.0.0 ngrx-vis /home/carlos/www/github/caballerog/ngrx-pokedex
> ngrx-vis -p ./tsconfig.app.json

/home/carlos/www/github/caballerog/ngrx-pokedex/node_modules/ngrx-vis/utils/ngrx.js:3
    var m = typeof Symbol === "function" && o[Symbol.iterator];
                                             ^

TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at __read (/home/carlos/www/github/caballerog/ngrx-pokedex/node_modules/ngrx-vis/utils/ngrx.js:3:46)
    at Object.segmentAction (/home/carlos/www/github/caballerog/ngrx-pokedex/node_modules/ngrx-vis/utils/ngrx.js:39:14)
    at /home/carlos/www/github/caballerog/ngrx-pokedex/node_modules/ngrx-vis/core/ngrx-vanilla-inspector.js:41:198
    at Array.map (<anonymous>)
    at NgRxVanillaInspector.findActions (/home/carlos/www/github/caballerog/ngrx-pokedex/node_modules/ngrx-vis/core/ngrx-vanilla-inspector.js:41:14)
    at /home/carlos/www/github/caballerog/ngrx-pokedex/node_modules/ngrx-vis/core/ngrx-vanilla-inspector.js:34:61
    at Array.flatMap (<anonymous>)
    at NgRxVanillaInspector.inspect (/home/carlos/www/github/caballerog/ngrx-pokedex/node_modules/ngrx-vis/core/ngrx-vanilla-inspector.js:34:22)
    at Object.<anonymous> (/home/carlos/www/github/caballerog/ngrx-pokedex/node_modules/ngrx-vis/index.js:20:32)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
```

Node version:
```
 node -v
v12.13.0
```
Thanks!

**Comment by GregOnNet** [comment]
Hi @Caballerog,

thank you so much for your report.
Currently, NgRx Vis is not capable of identifying actions being defined in nested data structures.

```
const actions = {
  load: createAction(...()
} // does not work, yet.
``` 

However, in version 0.1.22 I added an error message that provides more context.

![image](https://user-images.githubusercontent.com/444278/78558058-3d374c00-7812-11ea-989b-ff7a7bae532d.png)

I will link this issue to an existing one, where I will have to deal with the same challenge.
